[theme]
primaryColor = "#ff4b4b"
backgroundColor = "#667eea"
secondaryBackgroundColor = "#ffffff"
textColor = "#ffffff"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
headless = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false
